src = ["src"]

# Use Ruff for sorting imports
lint.extend-select = ["I"]

lint.ignore = [] # add E501 to avoid enforcing line length

[lint.per-file-ignores]
# Do not enforce usage and import order rules in init files
"__init__.py" = ["E402", "F401", "I"]
"main.py" = ["E402", "F401", "I"]

# Do not fix import in compatibility module
"src/python_pack/**/compat.py" = ["F401", "I"]

# Allow wild imports in conftest
"tests/conftest.py" = ["F405", "E402", "F403"]

# Allow fake items in __all__ for runtime
"src/python_pack/utils.py" = ["F822"]

# Do not enforce line length limits in migrations
"src/python_pack/**/database/migrations/**/*" = ["E501"]

[lint.isort]
known-third-party = []
